# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        rules:
            - { path: ^/, fallback_format: json, priorities: [ json ] }
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
    body_listener: true
    param_fetcher_listener: true
