api_login_check:
    path: /api/login_check

list:
    type: rest
    resource: App\Controller\ListController
    prefix: api

task:
    type: rest
    resource: App\Controller\TaskController
    prefix: api

note:
    type: rest
    resource: App\Controller\NoteController
    prefix: api